


CREATE TABLE CIDADE (
CIDID INT IDENTITY (1,1) PRIMARY KEY,
CIDDESCRICAO VARCHAR (100) NOT NULL,
ESTID INT NOT NULL REFERENCES ESTADO(ESTID)
)
GO
SELECT * FROM ESTADO
SELECT * FROM CIDADE
INSERT CIDADE VALUES ('ESTANCIA',1)

   
CREATE TABLE TIPODOCUMENTO (
TIPID INT IDENTITY (1,1) PRIMARY KEY,
TIPDESCRICAO VARCHAR (100) UNIQUE, 
 )
GO
CREATE TABLE PESSOA(
PESID INT IDENTITY (1,1) PRIMARY KEY,
PESNOME VARCHAR (200) NOT NULL,
PESCPF VARCHAR (100) NOT NULL,
PESENDERECO VARCHAR (100) NOT NULL,
CIDID INT  NOT NULL ,
)

CREATE TABLE TIPOPESSOA(
 PROIDINT INT IDENTITY(1,1) PRIMARY KEY,
 TIPDescricao VARCHAR (100) 
 
 ) 
 GO


 CREATE TABLE PROCESSO (
 
 PROID INT IDENTITY (1,1) PRIMARY KEY,
 PRORELATO VARCHAR (1000),
 PRODATA DATETIME,
)
GO
CREATE TABLE TIPOPESSOA(
TIPID INT IDENTITY (1,1) PRIMARY KEY,
TIPDESCRICAO VARCHAR (100) NOT NULL

)
CREATE TABLE PESSOAPROCESSO(
PESID INT NOT NULL,
PROID INT NOT NULL,
TIPID INT NOT NULL,
CONSTRAINT PK_PESSOAPROCESSO PRIMARY KEY (PESID, PROID),

CONSTRAINT FK_PESSOAPROCESSO_PESSOA FOREIGN KEY (PESID)
REFERENCES PESSOA (PESID),
CONSTRAINT FK_PESSOAPROCESSO_PROID FOREIGN KEY (PROID)
REFERENCES PROCESSO (PROID),
CONSTRAINT FK_PESSOAPROCESSO_TIPO FOREIGN KEY (TIPID)
REFERENCES TIPOPESSOA (TIPID),

)

CREATE TABLE PESSOA (
PESID INT IDENTITY (1,1) PRIMARY KEY,
PESNOME VARCHAR (100) NOT NULL,
PESCPF  VARCHAR (20) NOT NULL,
PESCNPJ VARCHAR (20),
PESEXO VARCHAR (100) NOT NULL,


)

 ALTER TABLE PESSOA
ADD PESTELEFONE VARCHAR(30);

INSERT PESSOA (PESNOME,PESCPF,PESCNPJ,PESEXO)
VALUES ('REGI','05156',  NULL,'INDECISO')

GO
INSERT TIPOPESSOA VALUES ('REU')
GO
INSERT PROCESSO VALUES ('GOTA SERENA', getDate())

select * from pessoa
select * from processo
select * from TIPOPESSOA
insert PESSOAPROCESSO values (1,1,1,GETDATE())
insert PESSOAPROCESSO values (1,2,1,GETDATE()) 

